import { NextResponse } from 'next/server';
import { checkOllamaHealth, ollamaGenerate } from '@/lib/ollama';

// =====================================================
// POST /api/prd — Auto PRD Generator
// ─────────────────────────────────────────────────────
// Generates a full Product Requirements Document from
// a feature idea + research context
// =====================================================

export async function POST(req: Request) {
    try {
        const { featureTitle, featureDescription, researchContext, painPoints } = await req.json();

        if (!featureTitle) {
            return NextResponse.json({ error: 'featureTitle is required' }, { status: 400 });
        }

        const ollamaStatus = await checkOllamaHealth();
        if (!ollamaStatus.available) {
            return NextResponse.json({
                success: true,
                source: 'template',
                prd: generateTemplatePRD(featureTitle, featureDescription),
            });
        }

        const contextBlock = researchContext
            ? `\nResearch Context:\n${researchContext.substring(0, 2000)}`
            : '';

        const painBlock = painPoints?.length
            ? `\nKnown Pain Points:\n${painPoints.map((p: string) => `- ${p}`).join('\n')}`
            : '';

        const prompt = `You are a senior Product Manager. Generate a complete, professional Product Requirements Document (PRD) for the following feature.

Feature: ${featureTitle}
${featureDescription ? `Description: ${featureDescription}` : ''}
${contextBlock}
${painBlock}

Write the PRD in markdown format with these sections:

# PRD: ${featureTitle}

## 1. Problem Statement
Clearly define the problem this feature solves.

## 2. Proposed Solution
Describe the solution in detail.

## 3. User Stories
List 3-5 user stories in "As a [user], I want [action], so that [benefit]" format.

## 4. Acceptance Criteria
Define clear success criteria.

## 5. Success Metrics
List measurable KPIs to track.

## 6. Technical Considerations
Note any technical requirements or constraints.

## 7. Dependencies & Risks
List dependencies and potential risks.

## 8. Timeline Estimate
Provide a rough estimation.

Be specific and professional. Base insights on the research context if provided.`;

        const prd = await ollamaGenerate(prompt, ollamaStatus.model);

        return NextResponse.json({
            success: true,
            source: 'ollama',
            model: ollamaStatus.model,
            prd,
        });

    } catch (error: any) {
        console.error('[PRD ERROR]', error);
        return NextResponse.json({ error: error.message || 'PRD generation failed' }, { status: 500 });
    }
}

function generateTemplatePRD(title: string, description?: string): string {
    return `# PRD: ${title}

## 1. Problem Statement
${description || 'To be defined based on research analysis.'}

## 2. Proposed Solution
Implement ${title} to address identified user pain points.

## 3. User Stories
- As a product user, I want ${title.toLowerCase()}, so that I can improve my workflow.
- As a team lead, I want visibility into ${title.toLowerCase()}, so that I can make data-driven decisions.
- As an admin, I want to configure ${title.toLowerCase()}, so that it fits our team's needs.

## 4. Acceptance Criteria
- [ ] Feature is functional and tested
- [ ] Documentation is updated
- [ ] Performance targets met

## 5. Success Metrics
- Adoption rate within 30 days
- Task completion time reduction
- User satisfaction score

## 6. Technical Considerations
- Integration with existing architecture
- Performance optimization needed
- Security and access control

## 7. Dependencies & Risks
- Dependency on backend API availability
- Risk: timeline pressure

## 8. Timeline Estimate
- Phase 1 (MVP): 2-3 weeks
- Phase 2 (Enhancement): 2 weeks

---
*Generated by Cursor PM AI (template mode — start Ollama for AI-powered PRD)*`;
}
