"use client";

import React, { useState, useEffect, useRef } from "react";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { useAuth } from "@/contexts/AuthContext";
import { motion, AnimatePresence, Variants } from "framer-motion";
import {
    Lightbulb, Target, ChevronDown, Loader2,
    ShieldAlert, Sparkles, FileText, ArrowRight, BarChart2, Cpu, Zap, GripVertical,
    FlaskConical, Shield, Map, Calculator, Download, Copy, Check, AlertTriangle,
    Rocket, Clock, Users, TrendingUp
} from "lucide-react";
import { getResearchByWorkspace } from "@/lib/firebase/researchService";
import { ResearchItem } from "@/types/research";
import { useSearchParams } from "next/navigation";
import { ReactSortable } from "react-sortablejs";
import { Doughnut, Bar } from 'react-chartjs-2';
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement } from 'chart.js';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement);

// ═══════════════════════════════════════════════════════
// MODULE 6: ADVANCED STRATEGY PLANNER
// ─────────────────────────────────────────────────────
// Features: Hypothesis, User Stories, OKRs, RICE
// Prioritization, Roadmap, Experiments, Risks, PRD
// ═══════════════════════════════════════════════════════

interface Hypothesis {
    id: string; workspaceId: string; title: string;
    solution: string; benefit: string; need: string;
    confidence: 'low' | 'medium' | 'high';
    sourceResearchIds: string[]; status: 'draft' | 'validated' | 'rejected'; createdAt: Date;
}

interface Strategy {
    hypothesis: Hypothesis;
    userStories: { id: string; text: string; priority: 'high' | 'medium' | 'low' }[];
    okrs: { objective: string; keyResults: string[] }[];
    source?: 'ollama' | 'template';
    ollamaModel?: string | null;
}

interface RICEFeature {
    id: string; name: string; reach: number; impact: number; confidence: number; effort: number; riceScore: number;
}

interface Experiment {
    id: string; name: string; hypothesis: string; metric: string; sampleSize: string; duration: string; status: 'planned' | 'running' | 'complete';
}

interface RiskItem {
    id: string; risk: string; impact: 'high' | 'medium' | 'low'; probability: 'high' | 'medium' | 'low'; recommendation: string;
}

function getConfidence(count: number): 'low' | 'medium' | 'high' {
    return count >= 5 ? 'high' : count >= 2 ? 'medium' : 'low';
}

export default function StrategyPlannerPage() {
    const { activeWorkspace } = useWorkspace();
    const { user } = useAuth();
    const searchParams = useSearchParams();
    const focusItemId = searchParams.get('itemId');
    const autoGeneratedRef = useRef(false);

    const [researchItems, setResearchItems] = useState<ResearchItem[]>([]);
    const [strategy, setStrategy] = useState<Strategy | null>(null);
    const [generating, setGenerating] = useState(false);
    const [loading, setLoading] = useState(true);
    const [generateError, setGenerateError] = useState('');
    const [activeSection, setActiveSection] = useState<string>('hypothesis');

    // Advanced Features State
    const [riceFeatures, setRiceFeatures] = useState<RICEFeature[]>([]);
    const [experiments, setExperiments] = useState<Experiment[]>([]);
    const [risks, setRisks] = useState<RiskItem[]>([]);
    const [prdContent, setPrdContent] = useState<string>('');
    const [prdLoading, setPrdLoading] = useState(false);
    const [prdCopied, setPrdCopied] = useState(false);
    const [roadmap, setRoadmap] = useState<{ q1: string[]; q2: string[]; q3: string[]; q4: string[] }>({ q1: [], q2: [], q3: [], q4: [] });
    const [activeTab, setActiveTab] = useState<'strategy' | 'prioritize' | 'roadmap' | 'experiments' | 'prd'>('strategy');

    // ── Strategy Generator ──
    const callGenerateAPI = async (items: ResearchItem[]): Promise<Strategy | null> => {
        const analyzed = items.filter(i => i.status === 'analyzed');
        if (analyzed.length === 0) return null;

        const allThemes: string[] = [];
        const themeSeen = new Set<string>();
        for (const item of analyzed) {
            for (const theme of (item.themes || [])) {
                if (!themeSeen.has(theme)) { themeSeen.add(theme); allThemes.push(theme); }
            }
        }
        if (allThemes.length === 0) return null;

        const researchSummaries = analyzed.map(i => i.summary || i.content || '').filter(Boolean);
        const confidence = getConfidence(analyzed.length);

        const res = await fetch('/api/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ themes: allThemes, researchSummaries, analyzedCount: analyzed.length, workspaceId: activeWorkspace?.id || '' }),
        });
        if (!res.ok) throw new Error(`Strategy generation failed: ${res.status}`);
        const data = await res.json();
        if (!data.success) throw new Error(data.error || 'API error');

        const { hypothesis, userStories, okrs, risks, experiments } = data.strategy;

        // 1. Process RICE scores from stories
        const riceItems: RICEFeature[] = (userStories || []).map((s: any, i: number) => {
            const { r, i: imp, c, e } = s.rice || { r: 1000, i: 2, c: 0.8, e: 2 };
            return {
                id: `rice-${Date.now()}-${i}`,
                name: s.text.length > 80 ? s.text.substring(0, 80) + '...' : s.text,
                reach: r, impact: imp, confidence: c * 100, effort: e,
                riceScore: Math.round((r * imp * c) / e),
            };
        });
        setRiceFeatures(riceItems.sort((a, b) => b.riceScore - a.riceScore));

        // 2. Process experiments
        const expItems: Experiment[] = (experiments || []).map((ex: any, i: number) => ({
            id: `exp-${Date.now()}-${i}`,
            name: ex.title,
            hypothesis: ex.hypothesis,
            metric: ex.metric,
            sampleSize: '500 users',
            duration: '2 weeks',
            status: 'planned' as const,
        }));
        setExperiments(expItems);

        // 3. Process risks
        const riskItems: RiskItem[] = (risks || []).map((r: string, i: number) => ({
            id: `risk-${i}`,
            risk: r,
            impact: i === 0 ? 'high' : 'medium',
            probability: i === 1 ? 'high' : 'medium',
            recommendation: 'Plan mitigation and track early metrics'
        }));
        setRisks(riskItems);

        // Auto-generate roadmap
        const storyTexts = (userStories || []).map((s: any) => {
            const text = typeof s === 'string' ? s : s.text;
            return text.length > 50 ? text.substring(0, 50) + '...' : text;
        });
        setRoadmap({
            q1: storyTexts.slice(0, 2),
            q2: storyTexts.slice(2, 4),
            q3: storyTexts.slice(4, 5),
            q4: ['Iterate and improve based on experiments'],
        });

        return {
            hypothesis: {
                id: `hyp_${Date.now()}`, workspaceId: activeWorkspace?.id || '',
                title: hypothesis.title, solution: hypothesis.solution,
                benefit: hypothesis.benefit, need: hypothesis.need,
                confidence, sourceResearchIds: analyzed.map(i => i.id),
                status: 'draft', createdAt: new Date(),
            },
            userStories: (userStories || []).map((s: any, i: number) => ({
                id: `story-${Date.now()}-${i}`,
                text: typeof s === 'string' ? s : s.text,
                priority: i === 0 ? 'high' : i === 1 ? 'medium' : 'low' as const,
            })),
            okrs: okrs || [],
            source: data.source,
            ollamaModel: data.ollamaModel,
        };
    };

    useEffect(() => {
        if (!activeWorkspace) { setLoading(false); return; }
        getResearchByWorkspace(activeWorkspace.id).then(async items => {
            setResearchItems(items);
            if (focusItemId && !autoGeneratedRef.current) {
                autoGeneratedRef.current = true;
                const targetItems = items.filter(i => i.id === focusItemId);
                if (targetItems.length > 0 && targetItems[0].status === 'analyzed') {
                    setGenerating(true);
                    try { const gen = await callGenerateAPI(targetItems); if (gen) setStrategy(gen); }
                    catch (err: any) { setGenerateError(err.message || 'Failed'); }
                    finally { setGenerating(false); }
                }
            }
        }).finally(() => setLoading(false));
    }, [activeWorkspace, focusItemId]);

    const handleGenerate = async () => {
        setGenerating(true); setGenerateError('');
        try { const gen = await callGenerateAPI(researchItems); setStrategy(gen); }
        catch (err: any) { setGenerateError(err.message || 'Failed'); }
        finally { setGenerating(false); }
    };

    // ── PRD Generator ──
    const handleGeneratePRD = async () => {
        if (!strategy) return;
        setPrdLoading(true);
        try {
            const res = await fetch('/api/prd', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    featureTitle: strategy.hypothesis.title,
                    featureDescription: strategy.hypothesis.solution,
                    painPoints: researchItems.filter(i => i.themes).flatMap(i => i.themes || []).slice(0, 5),
                }),
            });
            const data = await res.json();
            if (data.prd) { setPrdContent(data.prd); setActiveTab('prd'); }
        } catch (err) { console.error('PRD failed:', err); }
        finally { setPrdLoading(false); }
    };

    const handleCopyPRD = () => {
        navigator.clipboard.writeText(prdContent);
        setPrdCopied(true);
        setTimeout(() => setPrdCopied(false), 2000);
    };

    const analyzedCount = researchItems.filter(i => i.status === 'analyzed').length;

    const containerVariants: Variants = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.1 } } };
    const itemVariants: Variants = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 300, damping: 24 } } };

    if (!activeWorkspace) {
        return (
            <div className="flex h-[80vh] items-center justify-center">
                <div className="text-center space-y-4">
                    <ShieldAlert className="w-12 h-12 text-zinc-400 mx-auto opacity-50" />
                    <h2 className="text-xl font-bold text-zinc-500">No Environment Active</h2>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-[1200px] mx-auto pb-20">
            {/* Header */}
            <header className="mb-8">
                <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-500 mb-4">
                    <Target className="w-3.5 h-3.5" />
                    <span className="text-[11px] font-bold uppercase tracking-wider">Module 6: AI Strategy Engine</span>
                </div>
                <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-zinc-900 dark:text-white mb-3">Strategy Planner</h1>
                <p className="text-lg text-zinc-500 dark:text-zinc-400 max-w-2xl leading-relaxed">
                    AI-powered product strategy: hypotheses, OKRs, prioritization, roadmaps, experiments, and auto-generated PRDs.
                </p>
            </header>

            {/* Tab Navigation */}
            <div className="flex items-center gap-1 mb-8 p-1.5 bg-zinc-100 dark:bg-white/5 rounded-2xl w-fit border border-zinc-200/50 dark:border-white/5 overflow-x-auto">
                {[
                    { id: 'strategy' as const, label: 'Strategy', icon: Lightbulb },
                    { id: 'prioritize' as const, label: 'RICE Prioritize', icon: Calculator },
                    { id: 'roadmap' as const, label: 'Roadmap', icon: Map },
                    { id: 'experiments' as const, label: 'Experiments', icon: FlaskConical },
                    { id: 'prd' as const, label: 'PRD Generator', icon: FileText },
                ].map(tab => (
                    <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                        className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-[12px] font-bold transition-all whitespace-nowrap ${activeTab === tab.id
                            ? 'bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white shadow-sm border border-zinc-200/50 dark:border-white/10'
                            : 'text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300'}`}>
                        <tab.icon className="w-3.5 h-3.5" /> {tab.label}
                    </button>
                ))}
            </div>

            {/* Generate Banner */}
            <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}
                className="mb-8 bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[20px] p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 shadow-sm">
                <div className="flex items-center gap-4">
                    <div className="w-10 h-10 rounded-xl bg-purple-50 dark:bg-purple-500/10 border border-purple-200 dark:border-purple-500/20 flex items-center justify-center">
                        <Cpu className="w-5 h-5 text-purple-600 dark:text-purple-400" />
                    </div>
                    <div>
                        <h3 className="font-bold text-zinc-900 dark:text-white text-sm">Intelligence Status</h3>
                        <p className="text-[12px] text-zinc-500">{analyzedCount > 0 ? `${analyzedCount} docs ready` : 'No analyzed research yet.'}</p>
                    </div>
                </div>
                <div className="flex gap-2">
                    <button onClick={handleGenerate} disabled={generating || analyzedCount === 0}
                        className="shrink-0 flex items-center gap-2 px-5 py-2.5 bg-zinc-900 dark:bg-white text-white dark:text-black font-bold text-[12px] rounded-xl shadow-lg hover:opacity-90 transition-opacity disabled:opacity-40">
                        {generating ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating...</> : <><Sparkles className="w-3.5 h-3.5" /> Generate Strategy</>}
                    </button>
                    {strategy && (
                        <button onClick={handleGeneratePRD} disabled={prdLoading}
                            className="shrink-0 flex items-center gap-2 px-5 py-2.5 bg-blue-600 text-white font-bold text-[12px] rounded-xl shadow-lg hover:opacity-90 transition-opacity disabled:opacity-40">
                            {prdLoading ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Building PRD...</> : <><FileText className="w-3.5 h-3.5" /> Generate PRD</>}
                        </button>
                    )}
                </div>
            </motion.div>

            {/* Source Badge */}
            {strategy?.source && (
                <div className="mb-6">
                    <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[11px] font-bold border ${strategy.source === 'ollama'
                        ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-600 dark:text-emerald-400'
                        : 'bg-zinc-100 dark:bg-white/5 border-zinc-200 dark:border-white/10 text-zinc-500'}`}>
                        <Zap className="w-3 h-3" /> {strategy.source === 'ollama' ? `Generated by Qwen (${strategy.ollamaModel || 'qwen2.5'})` : 'Template Strategy'}
                    </span>
                </div>
            )}

            {generateError && (
                <div className="mb-6 p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 text-[12px] font-bold flex items-center gap-2">⚠ {generateError}</div>
            )}

            {/* ═══════════════ STRATEGY TAB ═══════════════ */}
            {activeTab === 'strategy' && (
                <>
                    {loading || generating ? (
                        <div className="py-20 flex flex-col items-center justify-center gap-4">
                            <Loader2 className="w-8 h-8 text-purple-500 animate-spin" />
                            {generating && <p className="text-sm font-bold text-zinc-500 animate-pulse">Building strategy with Qwen...</p>}
                        </div>
                    ) : !strategy ? (
                        <div className="py-16 text-center border-2 border-dashed border-zinc-200 dark:border-white/5 rounded-2xl space-y-3">
                            <Lightbulb className="w-10 h-10 text-zinc-300 mx-auto" />
                            <p className="text-lg font-bold text-zinc-400">No strategy generated yet</p>
                            <p className="text-[13px] text-zinc-400 max-w-md mx-auto">Upload & analyze research, then click Generate Strategy.</p>
                        </div>
                    ) : (
                        <motion.div variants={containerVariants} initial="hidden" animate="show" className="space-y-5">
                            {/* Hypothesis */}
                            <motion.div variants={itemVariants} className="bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[24px] overflow-hidden shadow-sm">
                                <button onClick={() => setActiveSection(activeSection === 'hypothesis' ? '' : 'hypothesis')}
                                    className="w-full flex items-center justify-between p-5 text-left hover:bg-zinc-50 dark:hover:bg-white/[0.02] transition-colors">
                                    <div className="flex items-center gap-3">
                                        <div className="w-9 h-9 rounded-xl bg-purple-100 dark:bg-purple-500/10 flex items-center justify-center border border-purple-200 dark:border-purple-500/20">
                                            <Lightbulb className="w-4 h-4 text-purple-500" />
                                        </div>
                                        <div>
                                            <h2 className="font-bold text-zinc-900 dark:text-white">AI Hypothesis</h2>
                                            <p className="text-[11px] text-zinc-500">Based on {strategy.hypothesis.sourceResearchIds.length} research items</p>
                                        </div>
                                    </div>
                                    <ChevronDown className={`w-4 h-4 text-zinc-400 transition-transform ${activeSection === 'hypothesis' ? 'rotate-180' : ''}`} />
                                </button>
                                <AnimatePresence>
                                    {activeSection === 'hypothesis' && (
                                        <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
                                            <div className="px-5 pb-5 space-y-4 border-t border-zinc-200/50 dark:border-white/10 pt-4">
                                                <div className="p-4 rounded-xl bg-purple-50 dark:bg-purple-500/5 border border-purple-100 dark:border-purple-500/10 text-[14px] leading-relaxed text-zinc-800 dark:text-zinc-200">
                                                    <span className="font-bold text-purple-600 dark:text-purple-400">If we </span>{strategy.hypothesis.solution},
                                                    <span className="font-bold text-emerald-600 dark:text-emerald-400"> then </span>{strategy.hypothesis.benefit}
                                                    <span className="font-bold text-blue-600 dark:text-blue-400"> because </span>{strategy.hypothesis.need}.
                                                </div>
                                                <div className="flex items-center gap-3">
                                                    <span className="text-[11px] font-bold text-zinc-500 uppercase tracking-wider">Confidence:</span>
                                                    <span className={`px-2.5 py-1 rounded-full text-[11px] font-bold uppercase border ${strategy.hypothesis.confidence === 'high' ? 'bg-emerald-100 dark:bg-emerald-500/10 text-emerald-600 border-emerald-200 dark:border-emerald-500/20' : strategy.hypothesis.confidence === 'medium' ? 'bg-orange-100 dark:bg-orange-500/10 text-orange-600 border-orange-200 dark:border-orange-500/20' : 'bg-zinc-100 dark:bg-white/5 text-zinc-500 border-zinc-200 dark:border-white/10'}`}>
                                                        {strategy.hypothesis.confidence}
                                                    </span>
                                                </div>
                                            </div>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>

                            {/* User Stories */}
                            <motion.div variants={itemVariants} className="bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[24px] overflow-hidden shadow-sm">
                                <button onClick={() => setActiveSection(activeSection === 'stories' ? '' : 'stories')}
                                    className="w-full flex items-center justify-between p-5 text-left hover:bg-zinc-50 dark:hover:bg-white/[0.02] transition-colors">
                                    <div className="flex items-center gap-3">
                                        <div className="w-9 h-9 rounded-xl bg-blue-100 dark:bg-blue-500/10 flex items-center justify-center border border-blue-200 dark:border-blue-500/20">
                                            <FileText className="w-4 h-4 text-blue-500" />
                                        </div>
                                        <div><h2 className="font-bold text-zinc-900 dark:text-white">User Stories</h2><p className="text-[11px] text-zinc-500">{strategy.userStories.length} stories · Drag to reorder</p></div>
                                    </div>
                                    <ChevronDown className={`w-4 h-4 text-zinc-400 transition-transform ${activeSection === 'stories' ? 'rotate-180' : ''}`} />
                                </button>
                                <AnimatePresence>
                                    {activeSection === 'stories' && (
                                        <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
                                            <div className="px-5 pb-5 space-y-2 border-t border-zinc-200/50 dark:border-white/10 pt-4">
                                                <ReactSortable list={strategy.userStories} setList={(newList) => setStrategy({ ...strategy, userStories: newList })} animation={200} className="space-y-2">
                                                    {strategy.userStories.map((story, i) => (
                                                        <div key={story.id} className="flex items-start gap-3 p-3 rounded-xl border border-zinc-200/50 dark:border-white/5 bg-zinc-50 dark:bg-white/[0.02] hover:border-blue-400/50 transition-colors cursor-grab active:cursor-grabbing">
                                                            <GripVertical className="w-4 h-4 text-zinc-300 dark:text-zinc-600 shrink-0 mt-0.5" />
                                                            <p className="flex-1 text-[13px] text-zinc-700 dark:text-zinc-300 leading-relaxed">{story.text}</p>
                                                            <span className={`shrink-0 px-2 py-0.5 rounded text-[9px] font-bold uppercase ${i === 0 ? 'bg-red-100 text-red-600' : i === 1 ? 'bg-orange-100 text-orange-600' : 'bg-zinc-100 text-zinc-500'}`}>
                                                                {i === 0 ? 'P1' : i === 1 ? 'P2' : 'Backlog'}
                                                            </span>
                                                        </div>
                                                    ))}
                                                </ReactSortable>
                                            </div>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>

                            {/* OKRs */}
                            <motion.div variants={itemVariants} className="bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[24px] overflow-hidden shadow-sm">
                                <button onClick={() => setActiveSection(activeSection === 'okrs' ? '' : 'okrs')}
                                    className="w-full flex items-center justify-between p-5 text-left hover:bg-zinc-50 dark:hover:bg-white/[0.02] transition-colors">
                                    <div className="flex items-center gap-3">
                                        <div className="w-9 h-9 rounded-xl bg-emerald-100 dark:bg-emerald-500/10 flex items-center justify-center border border-emerald-200 dark:border-emerald-500/20">
                                            <Target className="w-4 h-4 text-emerald-500" />
                                        </div>
                                        <div><h2 className="font-bold text-zinc-900 dark:text-white">OKRs</h2><p className="text-[11px] text-zinc-500">Objectives & Key Results</p></div>
                                    </div>
                                    <ChevronDown className={`w-4 h-4 text-zinc-400 transition-transform ${activeSection === 'okrs' ? 'rotate-180' : ''}`} />
                                </button>
                                <AnimatePresence>
                                    {activeSection === 'okrs' && (
                                        <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
                                            <div className="px-5 pb-5 space-y-5 border-t border-zinc-200/50 dark:border-white/10 pt-4">
                                                {strategy.okrs.map((okr, i) => (
                                                    <div key={i} className="space-y-3">
                                                        <div className="flex items-start gap-2">
                                                            <Target className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                                                            <div>
                                                                <p className="text-[10px] font-bold uppercase tracking-widest text-emerald-500 mb-0.5">Objective</p>
                                                                <p className="font-bold text-zinc-900 dark:text-white text-[14px]">{okr.objective}</p>
                                                            </div>
                                                        </div>
                                                        <div className="ml-6 space-y-2">
                                                            {okr.keyResults.map((kr, j) => (
                                                                <div key={j} className="flex items-start gap-2 p-3 rounded-xl bg-zinc-50 dark:bg-white/[0.02] border border-zinc-200/50 dark:border-white/5">
                                                                    <BarChart2 className="w-3.5 h-3.5 text-zinc-400 shrink-0 mt-0.5" />
                                                                    <p className="text-[13px] text-zinc-700 dark:text-zinc-300">{kr}</p>
                                                                </div>
                                                            ))}
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>

                            {/* Risks */}
                            {risks.length > 0 && (
                                <motion.div variants={itemVariants} className="bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[24px] overflow-hidden shadow-sm">
                                    <button onClick={() => setActiveSection(activeSection === 'risks' ? '' : 'risks')}
                                        className="w-full flex items-center justify-between p-5 text-left hover:bg-zinc-50 dark:hover:bg-white/[0.02] transition-colors">
                                        <div className="flex items-center gap-3">
                                            <div className="w-9 h-9 rounded-xl bg-red-100 dark:bg-red-500/10 flex items-center justify-center border border-red-200 dark:border-red-500/20">
                                                <Shield className="w-4 h-4 text-red-500" />
                                            </div>
                                            <div><h2 className="font-bold text-zinc-900 dark:text-white">Risk Analysis</h2><p className="text-[11px] text-zinc-500">{risks.length} risks identified</p></div>
                                        </div>
                                        <ChevronDown className={`w-4 h-4 text-zinc-400 transition-transform ${activeSection === 'risks' ? 'rotate-180' : ''}`} />
                                    </button>
                                    <AnimatePresence>
                                        {activeSection === 'risks' && (
                                            <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
                                                <div className="px-5 pb-5 space-y-3 border-t border-zinc-200/50 dark:border-white/10 pt-4">
                                                    {risks.map(r => (
                                                        <div key={r.id} className="flex items-start gap-3 p-3 rounded-xl bg-red-50 dark:bg-red-500/5 border border-red-100 dark:border-red-500/10">
                                                            <AlertTriangle className={`w-4 h-4 shrink-0 mt-0.5 ${r.impact === 'high' ? 'text-red-500' : 'text-orange-500'}`} />
                                                            <div className="flex-1">
                                                                <p className="font-bold text-zinc-900 dark:text-white text-[13px]">{r.risk}</p>
                                                                <p className="text-[11px] text-emerald-600 mt-1">→ {r.recommendation}</p>
                                                            </div>
                                                            <span className={`px-2 py-0.5 rounded-full text-[9px] font-bold uppercase ${r.impact === 'high' ? 'bg-red-100 text-red-600' : r.impact === 'medium' ? 'bg-orange-100 text-orange-600' : 'bg-zinc-100 text-zinc-500'}`}>{r.impact}</span>
                                                        </div>
                                                    ))}
                                                </div>
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </motion.div>
                            )}
                        </motion.div>
                    )}
                </>
            )}

            {/* ═══════════════ RICE PRIORITIZATION TAB ═══════════════ */}
            {activeTab === 'prioritize' && (
                <div className="space-y-5">
                    {riceFeatures.length === 0 ? (
                        <div className="py-16 text-center border-2 border-dashed border-zinc-200 dark:border-white/5 rounded-2xl space-y-3">
                            <Calculator className="w-10 h-10 text-zinc-300 mx-auto" />
                            <p className="text-lg font-bold text-zinc-400">Generate a strategy first</p>
                            <p className="text-[13px] text-zinc-400">RICE scores are auto-generated from user stories.</p>
                        </div>
                    ) : (
                        <>
                            <div className="bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[24px] p-5 shadow-sm">
                                <h3 className="font-bold text-zinc-900 dark:text-white mb-4 flex items-center gap-2">
                                    <Calculator className="w-4 h-4 text-blue-500" /> RICE Prioritization Framework
                                </h3>
                                <div className="overflow-x-auto">
                                    <table className="w-full text-[12px]">
                                        <thead>
                                            <tr className="border-b border-zinc-200/50 dark:border-white/10">
                                                <th className="text-left py-3 px-3 font-bold text-zinc-500 uppercase tracking-wider text-[10px]">Feature</th>
                                                <th className="text-center py-3 px-2 font-bold text-zinc-500 uppercase tracking-wider text-[10px]">Reach</th>
                                                <th className="text-center py-3 px-2 font-bold text-zinc-500 uppercase tracking-wider text-[10px]">Impact</th>
                                                <th className="text-center py-3 px-2 font-bold text-zinc-500 uppercase tracking-wider text-[10px]">Confidence</th>
                                                <th className="text-center py-3 px-2 font-bold text-zinc-500 uppercase tracking-wider text-[10px]">Effort</th>
                                                <th className="text-center py-3 px-2 font-bold text-zinc-500 uppercase tracking-wider text-[10px]">RICE Score</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {riceFeatures.map((f, i) => (
                                                <tr key={f.id} className={`border-b border-zinc-100 dark:border-white/5 ${i === 0 ? 'bg-emerald-50/50 dark:bg-emerald-500/5' : ''}`}>
                                                    <td className="py-3 px-3 font-medium text-zinc-900 dark:text-white max-w-[300px]">{f.name}</td>
                                                    <td className="text-center py-3 px-2 text-zinc-600 dark:text-zinc-400">{f.reach.toLocaleString()}</td>
                                                    <td className="text-center py-3 px-2">
                                                        <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${f.impact >= 3 ? 'bg-emerald-100 text-emerald-600' : f.impact >= 2 ? 'bg-orange-100 text-orange-600' : 'bg-zinc-100 text-zinc-500'}`}>
                                                            {f.impact >= 3 ? 'High' : f.impact >= 2 ? 'Medium' : 'Low'}
                                                        </span>
                                                    </td>
                                                    <td className="text-center py-3 px-2 text-zinc-600 dark:text-zinc-400">{f.confidence}%</td>
                                                    <td className="text-center py-3 px-2 text-zinc-600 dark:text-zinc-400">{f.effort} person-months</td>
                                                    <td className="text-center py-3 px-2">
                                                        <span className="font-black text-zinc-900 dark:text-white text-[14px]">{f.riceScore.toLocaleString()}</span>
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            {/* RICE Chart */}
                            <div className="bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[24px] p-5 shadow-sm">
                                <h3 className="font-bold text-zinc-900 dark:text-white mb-4 text-sm">Score Distribution</h3>
                                <div className="h-[200px]">
                                    <Bar
                                        data={{
                                            labels: riceFeatures.map((f, i) => `Feature ${i + 1}`),
                                            datasets: [{
                                                label: 'RICE Score',
                                                data: riceFeatures.map(f => f.riceScore),
                                                backgroundColor: riceFeatures.map((_, i) => i === 0 ? 'rgba(16,185,129,0.7)' : i === 1 ? 'rgba(99,102,241,0.7)' : 'rgba(161,161,170,0.5)'),
                                                borderRadius: 6, borderSkipped: false,
                                            }]
                                        }}
                                        options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { y: { beginAtZero: true }, x: { grid: { display: false } } } }}
                                    />
                                </div>
                            </div>
                        </>
                    )}
                </div>
            )}

            {/* ═══════════════ ROADMAP TAB ═══════════════ */}
            {activeTab === 'roadmap' && (
                <div className="space-y-5">
                    {roadmap.q1.length === 0 && roadmap.q2.length === 0 ? (
                        <div className="py-16 text-center border-2 border-dashed border-zinc-200 dark:border-white/5 rounded-2xl space-y-3">
                            <Map className="w-10 h-10 text-zinc-300 mx-auto" />
                            <p className="text-lg font-bold text-zinc-400">Generate a strategy to see the roadmap</p>
                        </div>
                    ) : (
                        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
                            {[
                                { key: 'q1', label: 'Q1', color: 'emerald', icon: Rocket },
                                { key: 'q2', label: 'Q2', color: 'blue', icon: TrendingUp },
                                { key: 'q3', label: 'Q3', color: 'purple', icon: Users },
                                { key: 'q4', label: 'Q4', color: 'orange', icon: Target },
                            ].map(q => (
                                <motion.div key={q.key} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                                    className={`bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[20px] p-5 shadow-sm relative overflow-hidden min-h-[300px]`}>
                                    <div className={`absolute top-0 right-0 w-20 h-20 bg-${q.color}-500/10 blur-[30px] rounded-full`} />
                                    <div className="flex items-center gap-2 mb-4">
                                        <div className={`w-8 h-8 rounded-lg bg-${q.color}-100 dark:bg-${q.color}-500/10 flex items-center justify-center`}>
                                            <q.icon className={`w-4 h-4 text-${q.color}-500`} />
                                        </div>
                                        <h3 className="font-bold text-zinc-900 dark:text-white text-sm">{q.label}</h3>
                                    </div>
                                    <ReactSortable
                                        list={(roadmap as any)[q.key].map((text: string, id: number) => ({ id: `${q.key}-${id}`, text }))}
                                        setList={(newList) => setRoadmap(prev => ({ ...prev, [q.key]: newList.map(item => item.text) }))}
                                        group="roadmap-shared"
                                        animation={200}
                                        className="space-y-2 min-h-[200px]"
                                    >
                                        {(roadmap as any)[q.key].length === 0 ? (
                                            <p className="text-[12px] text-zinc-400 italic pointer-events-none py-4 text-center">Drop items here</p>
                                        ) : (
                                            (roadmap as any)[q.key].map((item: string, i: number) => (
                                                <div key={i} className="p-2.5 rounded-lg bg-zinc-50 dark:bg-white/[0.02] border border-zinc-200/50 dark:border-white/5 text-[12px] text-zinc-700 dark:text-zinc-300 font-medium cursor-grab active:cursor-grabbing hover:border-blue-400/50 transition-colors">
                                                    {item}
                                                </div>
                                            ))
                                        )}
                                    </ReactSortable>
                                </motion.div>
                            ))}
                        </div>
                    )}
                </div>
            )}

            {/* ═══════════════ EXPERIMENTS TAB ═══════════════ */}
            {activeTab === 'experiments' && (
                <div className="space-y-4">
                    {experiments.length === 0 ? (
                        <div className="py-16 text-center border-2 border-dashed border-zinc-200 dark:border-white/5 rounded-2xl space-y-3">
                            <FlaskConical className="w-10 h-10 text-zinc-300 mx-auto" />
                            <p className="text-lg font-bold text-zinc-400">Generate a strategy to see experiments</p>
                        </div>
                    ) : (
                        experiments.map(exp => (
                            <motion.div key={exp.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                                className="bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[20px] p-5 shadow-sm">
                                <div className="flex items-start justify-between mb-3">
                                    <h3 className="font-bold text-zinc-900 dark:text-white text-sm">{exp.name}</h3>
                                    <span className="px-2.5 py-1 rounded-full bg-blue-500/10 text-blue-600 dark:text-blue-400 text-[10px] font-bold uppercase border border-blue-500/20">{exp.status}</span>
                                </div>
                                <p className="text-[12px] text-zinc-500 mb-3 italic">&ldquo;{exp.hypothesis}&rdquo;</p>
                                <div className="grid grid-cols-3 gap-3">
                                    <div className="p-2.5 rounded-lg bg-zinc-50 dark:bg-white/[0.02] border border-zinc-200/50 dark:border-white/5">
                                        <p className="text-[9px] font-bold text-zinc-500 uppercase tracking-widest mb-0.5">Metric</p>
                                        <p className="text-[12px] font-bold text-zinc-900 dark:text-white">{exp.metric}</p>
                                    </div>
                                    <div className="p-2.5 rounded-lg bg-zinc-50 dark:bg-white/[0.02] border border-zinc-200/50 dark:border-white/5">
                                        <p className="text-[9px] font-bold text-zinc-500 uppercase tracking-widest mb-0.5">Sample</p>
                                        <p className="text-[12px] font-bold text-zinc-900 dark:text-white">{exp.sampleSize}</p>
                                    </div>
                                    <div className="p-2.5 rounded-lg bg-zinc-50 dark:bg-white/[0.02] border border-zinc-200/50 dark:border-white/5">
                                        <p className="text-[9px] font-bold text-zinc-500 uppercase tracking-widest mb-0.5">Duration</p>
                                        <p className="text-[12px] font-bold text-zinc-900 dark:text-white">{exp.duration}</p>
                                    </div>
                                </div>
                            </motion.div>
                        ))
                    )}
                </div>
            )}

            {/* ═══════════════ PRD TAB ═══════════════ */}
            {activeTab === 'prd' && (
                <div className="space-y-4">
                    {!prdContent ? (
                        <div className="py-16 text-center border-2 border-dashed border-zinc-200 dark:border-white/5 rounded-2xl space-y-3">
                            <FileText className="w-10 h-10 text-zinc-300 mx-auto" />
                            <p className="text-lg font-bold text-zinc-400">No PRD generated yet</p>
                            <p className="text-[13px] text-zinc-400 max-w-md mx-auto">Generate a strategy first, then click &ldquo;Generate PRD&rdquo;.</p>
                            {strategy && (
                                <button onClick={handleGeneratePRD} disabled={prdLoading}
                                    className="mt-3 px-6 py-3 bg-blue-600 text-white font-bold text-[13px] rounded-xl shadow-lg hover:opacity-90 transition-opacity disabled:opacity-40">
                                    {prdLoading ? <><Loader2 className="w-4 h-4 animate-spin inline mr-2" />Generating...</> : <><FileText className="w-4 h-4 inline mr-2" />Generate PRD</>}
                                </button>
                            )}
                        </div>
                    ) : (
                        <div className="bg-white dark:bg-[#0A0A0A] border border-zinc-200/80 dark:border-white/10 rounded-[24px] overflow-hidden shadow-sm">
                            <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-200/50 dark:border-white/10 bg-zinc-50/50 dark:bg-white/[0.02]">
                                <h3 className="font-bold text-zinc-900 dark:text-white flex items-center gap-2">
                                    <FileText className="w-4 h-4 text-blue-500" /> Auto-Generated PRD
                                </h3>
                                <div className="flex gap-2">
                                    <button onClick={handleCopyPRD}
                                        className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-100 dark:bg-white/5 text-zinc-600 dark:text-zinc-400 rounded-lg text-[11px] font-bold border border-zinc-200 dark:border-white/10 hover:bg-zinc-200 dark:hover:bg-white/10 transition-all">
                                        {prdCopied ? <><Check className="w-3 h-3 text-emerald-500" /> Copied!</> : <><Copy className="w-3 h-3" /> Copy</>}
                                    </button>
                                    <button onClick={handleGeneratePRD} disabled={prdLoading}
                                        className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-500/10 text-blue-600 dark:text-blue-400 rounded-lg text-[11px] font-bold border border-blue-500/20 hover:bg-blue-500/20 transition-all disabled:opacity-40">
                                        <Sparkles className="w-3 h-3" /> Regenerate
                                    </button>
                                </div>
                            </div>
                            <div className="p-6 prose prose-sm dark:prose-invert max-w-none text-[14px]">
                                <ReactMarkdown remarkPlugins={[remarkGfm]}>{prdContent}</ReactMarkdown>
                            </div>
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}
